server:
  autoscaling:
    enabled: true
    minReplicas: 2
  extraArgs: 
  - --insecure=true

  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-manager-letsencrypt-production-route53
    tls:
    - secretName: argocd-tls-certificate
      hosts:
        - ${hostname}
    hosts:
      - ${hostname}
    ingressClassName: nginx

redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
